# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production
  pool: 5
  username: root
  password: Roy@l4b@d!
  host: dbsaltic.royalcorp.co.id
  #host: 127.0.0.1
  #port: 3307

jdeoracle:
  adapter: oracle_enhanced
  username: JDE
  password: jdevg920
  database: "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=192.212.212.54)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ORCL)))"

sqlserver:
  adapter: sqlserver
  encoding: utf8
  reconnect: true
  database: DBMarketing
  pool: 5
  username: sa
  password: batosay*99
  host: 192.168.100.6
  port: 1433

pos:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: point_of_sales_staging
  pool: 5
  reconnect: true
  username: root
  password: royalabadi
  host: 192.168.101.220

bcp:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: point_of_sales_bcp
  pool: 5
  reconnect: true
  username: root
  password: royalabadi
  host: 192.168.101.220
